local M = {}

local rose_wood = function()
    local Color = require("color")

    local colors = {
        rosewater = "#66292F",
        flamingo = "#8A4B53",
        red = "#BF472C",
        maroon = "#ea6962",
        pink = "#8B3040",
        mauve = "#C4622D",
        peach = "#D47D49",
        yellow = "#F2A766",
        green = "#F2A766",
        teal = "#A67458",
        sky = "#A67458",
        sapphire = "#A67458",
        blue = "#D47D49",
        lavender = "#E0CCAE",
        text = "#F2DDBC",
        subtext1 = "#E0CCAE",
        subtext0 = "#A67458",
        overlay2 = "#a4896f",
        overlay1 = "#A4895C",
        overlay0 = "#6B4035",
        surface2 = "#3d231a",
        surface1 = "#291916",
        surface0 = "#1F1311",
        base = "#0F0908",
        mantle = "#121212",
        crust = "#141617",
    }

    local syntax = {
        keyword = Color:from_hex(colors.red):lighten(8):hex(),
        operator = colors.peach,
        func = Color:from_hex(colors.yellow):lighten(2):hex(),
        method = colors.yellow,
        string = Color:from_hex(colors.teal):lighten(10):hex(),
        property = colors.overlay2,
        type = colors.lavender,
        constant = Color:from_hex(colors.peach):lighten(8):hex(),
        number = Color:from_hex(colors.mauve):lighten(14):hex(),
        punctuation = colors.overlay0,
        variable = colors.text,
        parameter = Color:from_hex(colors.text):darken(8):hex(),
        comment = Color:from_hex(colors.overlay1):darken(8):hex(),
    }

    local selection_bg = Color:from_hex(colors.surface0):lighten(22):hex()
    local picker_selection_bg = Color:from_hex(colors.surface0):lighten(12):hex()
    local diff = {
        add = "#D9EE8D",
        add_bg = "#334D1B",
        add_word_bg = "#6B9430",
        change = "#F0A35F",
        change_bg = "#33200F",
        change_word_bg = "#70431F",
        delete = "#FF7658",
        delete_bg = "#4A1B12",
        delete_word_bg = "#923923",
    }

    require("rose-pine").setup({
        variant = "auto", -- auto, main, moon, or dawn
        dark_variant = "main", -- main, moon, or dawn
        palette = {
            main = {
                _nc = colors.mantle,
                base = colors.base,
                surface = colors.surface0,
                overlay = colors.surface1,
                muted = colors.overlay0,
                subtle = colors.overlay1,
                text = colors.text,
                love = colors.red,
                gold = colors.yellow,
                rose = colors.peach,
                pine = colors.teal,
                foam = colors.green,
                iris = colors.pink,
                leaf = colors.teal,
                highlight_low = colors.surface0,
                highlight_med = colors.surface1,
                highlight_high = colors.surface2,
                none = "NONE",
            },
        },
        highlight_groups = {
            HighlightYank = { bg = colors.overlay2 },
            LineNr = { fg = colors.overlay0 },
            TabLineFill = { bg = Color:from_hex(colors.base):hex() },
            WinBar = { bg = "NONE" },
            WinSeparator = { fg = colors.surface1 },
            StatusLine = { bg = "NONE" },
            StatusLineNC = { bg = "NONE" },
            CommentItalic = { fg = colors.overlay1, italic = true },
            CommentBg = { bg = colors.base, bold = true, fg = colors.overlay2 },
            StatusLineSeparator = { fg = Color:from_hex(colors.base):lighten(8):hex() },
            NormalFloat = { bg = colors.base, fg = colors.text },
            FloatBorder = { bg = "NONE", fg = colors.surface1 },
            FloatTitle = { bg = "NONE", fg = colors.yellow, bold = true },
            Cursor = { bg = colors.yellow, fg = colors.base },
            CursorLine = { bg = "NONE" },
            CursorLineNr = { fg = colors.text, bold = true },
            Visual = { bg = selection_bg },
            Pmenu = { bg = colors.base, fg = colors.text },
            PmenuSel = { bg = picker_selection_bg, fg = colors.yellow, bold = true },
            BlinkCmpMenuSelection = { bg = picker_selection_bg, fg = colors.yellow, bold = true },
            SnacksPicker = { bg = colors.base },
            SnacksPickerInput = { bg = colors.base },
            SnacksPickerList = { bg = colors.base },
            SnacksPickerPreview = { bg = colors.base },
            SnacksPickerBox = { bg = colors.base },
            SnacksPickerSelected = { bg = picker_selection_bg, fg = colors.yellow, bold = true },
            SnacksPickerCursorLine = { bg = picker_selection_bg },
            SnacksPickerListCursorLine = { bg = picker_selection_bg },
            SnacksPickerPreviewCursorLine = { bg = picker_selection_bg },
            Added = { fg = diff.add, bold = true },
            Changed = { fg = diff.change, bold = true },
            Removed = { fg = diff.delete, bold = true },
            DiffAdd = { fg = diff.add, bg = diff.add_bg },
            DiffChange = { fg = diff.change, bg = diff.change_bg },
            DiffDelete = { fg = diff.delete, bg = diff.delete_bg },
            DiffText = { fg = colors.text, bg = diff.change_word_bg, bold = true, underline = true },
            DiffTextAdd = { fg = colors.text, bg = diff.add_word_bg, bold = true, underline = true },
            CodeDiffLineInsert = { bg = diff.add_bg },
            CodeDiffLineDelete = { bg = diff.delete_bg },
            CodeDiffCharInsert = { bg = diff.add_word_bg },
            CodeDiffCharDelete = { bg = diff.delete_word_bg },
            diffAdded = { link = "DiffAdd" },
            diffChanged = { link = "DiffChange" },
            diffRemoved = { link = "DiffDelete" },
            ["@diff.plus"] = { fg = diff.add, bg = diff.add_bg, bold = true },
            ["@diff.minus"] = { fg = diff.delete, bg = diff.delete_bg, bold = true },
            ["@diff.delta"] = { fg = diff.change, bg = diff.change_bg, bold = true },
            ["@text.diff.add"] = { link = "DiffAdd" },
            ["@text.diff.delete"] = { link = "DiffDelete" },
            GitSignsAdd = { fg = diff.add, bg = "NONE", bold = true },
            GitSignsChange = { fg = diff.change, bg = "NONE", bold = true },
            GitSignsDelete = { fg = diff.delete, bg = "NONE", bold = true },
            GitSignsAddLn = { bg = diff.add_bg },
            GitSignsChangeLn = { bg = diff.change_bg },
            GitSignsDeleteLn = { bg = diff.delete_bg },
            GitSignsAddNr = { fg = diff.add, bold = true },
            GitSignsChangeNr = { fg = diff.change, bold = true },
            GitSignsDeleteNr = { fg = diff.delete, bold = true },
            NeogitDiffAdd = { link = "DiffAdd" },
            NeogitDiffDelete = { link = "DiffDelete" },
            NeogitDiffAddHighlight = { link = "DiffAdd" },
            NeogitDiffDeleteHighlight = { link = "DiffDelete" },
            NeogitDiffContextHighlight = { bg = colors.base },
            MiniDiffOverAdd = { fg = diff.add, bg = diff.add_bg, bold = true },
            MiniDiffOverChange = { fg = colors.text, bg = diff.delete_word_bg, bold = true, underline = true },
            MiniDiffOverChangeBuf = { fg = colors.text, bg = diff.add_word_bg, bold = true, underline = true },
            MiniDiffOverDelete = { fg = diff.delete, bg = diff.delete_bg, bold = true },
            MiniDiffOverAddText = { fg = colors.text, bg = diff.add_word_bg, bold = true, underline = true },
            MiniDiffOverChangeText = { fg = colors.text, bg = diff.change_word_bg, bold = true, underline = true },
            MiniDiffOverDeleteText = { fg = colors.text, bg = diff.delete_word_bg, bold = true, underline = true },
            MiniDiffOverContext = { bg = colors.base },
            MiniDiffOverContextBuf = { bg = colors.base },
            MiniDiffSignAdd = { fg = diff.add, bold = true },
            MiniDiffSignChange = { fg = diff.change, bold = true },
            MiniDiffSignDelete = { fg = diff.delete, bold = true },
            DeltaDiffAddedWord = { fg = colors.text, bg = diff.add_word_bg, bold = true, underline = true },
            DeltaDiffRemovedWord = { fg = colors.text, bg = diff.delete_word_bg, bold = true, underline = true },
            Folded = { link = "TextDimmer" },
            MsgArea = { link = "TextDim" },
            ModeMsg = { link = "TextDim" },
            CodeLensSeparator = { fg = colors.surface0 },
            CodeLensContentIcon = { fg = colors.green, bg = colors.surface0 },
            CodeLensContent = { fg = colors.overlay0, bg = colors.surface0, italic = true },
            StatusLineGreenTextNoBg = { link = "DiagnosticInfoTextNoBg" },
            StatusLineGreenTextWithBg = { link = "DiagnosticInfoTextWithBg" },
            StatusLineYellowTextNoBg = { link = "DiagnosticWarnTextNoBg" },
            StatusLineYellowTextWithBg = { link = "DiagnosticWarnTextWithBg" },
            StatusLineRedTextNoBg = { link = "DiagnosticErrorTextNoBg" },
            StatusLineRedTextWithBg = { link = "DiagnosticErrorTextWithBg" },
            DiagnosticInfoTextNoBg = { fg = "#1F1311" },
            DiagnosticInfoTextWithBg = { fg = "#A4895C", bg = "#1F1311", italic = true },
            DiagnosticErrorTextNoBg = { fg = "#2d1610" },
            DiagnosticErrorTextWithBg = { fg = "#BF472C", bg = "#2d1610", italic = true },
            DiagnosticWarnTextNoBg = { fg = "#1F1311" },
            DiagnosticWarnTextWithBg = { fg = "#D47D49", bg = "#1F1311", italic = true },
            DiagnosticHintTextNoBg = { fg = "#1F1311" },
            DiagnosticHintTextWithBg = { fg = "#A4895C", bg = "#1F1311", italic = true },

            OutlineGuides = { link = "TextDimmer" },
            OutlineFoldMarker = { link = "TextDimmer" },

            DiagnosticErrorDotOnErrorBg = { fg = "#BF472C", bg = "#2d1610", italic = true },
            DiagnosticWarnDotOnErrorBg = { fg = "#D47D49", bg = "#2d1610", italic = true },
            DiagnosticInfoDotOnErrorBg = { fg = "#A4895C", bg = "#2d1610", italic = true },
            DiagnosticHintDotOnErrorBg = { fg = "#A4895C", bg = "#2d1610", italic = true },

            DiagnosticErrorDotOnWarnBg = { fg = "#BF472C", bg = "#1F1311", italic = true },
            DiagnosticWarnDotOnWarnBg = { fg = "#D47D49", bg = "#1F1311", italic = true },
            DiagnosticInfoDotOnWarnBg = { fg = "#A4895C", bg = "#1F1311", italic = true },
            DiagnosticHintDotOnWarnBg = { fg = "#A4895C", bg = "#1F1311", italic = true },

            DiagnosticErrorDotOnInfoBg = { fg = "#BF472C", bg = "#1F1311", italic = true },
            DiagnosticWarnDotOnInfoBg = { fg = "#D47D49", bg = "#1F1311", italic = true },
            DiagnosticInfoDotOnInfoBg = { fg = "#A4895C", bg = "#1F1311", italic = true },
            DiagnosticHintDotOnInfoBg = { fg = "#A4895C", bg = "#1F1311", italic = true },

            DiagnosticErrorDotOnHintBg = { fg = "#BF472C", bg = "#1F1311", italic = true },
            DiagnosticWarnDotOnHintBg = { fg = "#D47D49", bg = "#1F1311", italic = true },
            DiagnosticInfoDotOnHintBg = { fg = "#A4895C", bg = "#1F1311", italic = true },
            DiagnosticHintDotOnHintBg = { fg = "#A4895C", bg = "#1F1311", italic = true },

            StatusLineSeparatorContent = {
                fg = colors.subtext1,
                bg = Color:from_hex(colors.base):lighten(8):hex(),
            },
            StatuslineSeparatorLsp = {
                fg = "#928375",
                bg = Color:from_hex(colors.base):lighten(8):hex(),
            },
            NormalMode = { fg = "#F2A766" },
            ReplaceMode = { fg = "#ea6963" },
            CommandMode = { fg = "#e78a4f" },
            PendingMode = { fg = "#D8A658" },
            InsertMode = { fg = "#a9b666" },
            VisualMode = { fg = "#D3869C" },
            MiniFilesTitleFocused = { link = "FloatTitle" },
            MiniIndentscopeSymbol = { link = "TextDimmest" },
            Text = { fg = colors.text },
            TextDim = { fg = "#928375" },
            TextDimmer = { fg = Color:from_hex("#928375"):darken(22):hex() },
            TextDimmest = { fg = Color:from_hex("#928375"):darken(33):hex() },

            Comment = { fg = syntax.comment, italic = true },
            Constant = { fg = syntax.constant },
            String = { fg = syntax.string, italic = true },
            Character = { link = "String" },
            Number = { fg = syntax.number },
            Boolean = { fg = syntax.number },
            Float = { link = "Number" },
            Identifier = { fg = syntax.variable },
            Function = { fg = syntax.func },
            Statement = { fg = syntax.keyword },
            Conditional = { fg = syntax.keyword, italic = true },
            Repeat = { fg = syntax.keyword, italic = true },
            Label = { fg = syntax.operator },
            Operator = { fg = syntax.operator },
            Keyword = { fg = syntax.keyword, italic = true },
            Exception = { fg = syntax.keyword },
            PreProc = { fg = syntax.operator },
            Include = { fg = syntax.keyword, italic = true },
            Define = { fg = syntax.operator },
            Macro = { fg = syntax.operator },
            Type = { fg = syntax.type },
            StorageClass = { fg = syntax.type, italic = true },
            Structure = { fg = syntax.type },
            Typedef = { fg = syntax.type },
            Special = { fg = syntax.constant },
            SpecialChar = { fg = syntax.constant },
            Delimiter = { fg = syntax.punctuation },

            TSAnnotation = { fg = syntax.operator },
            TSAttribute = { fg = syntax.property },
            TSBoolean = { link = "Boolean" },
            TSCharacter = { link = "Character" },
            TSComment = { link = "Comment" },
            TSConditional = { link = "Conditional" },
            TSConstant = { fg = syntax.constant },
            TSConstBuiltin = { fg = syntax.constant, italic = true },
            TSConstMacro = { link = "Macro" },
            TSConstructor = { fg = syntax.type },
            TSException = { link = "Exception" },
            TSField = { fg = syntax.property },
            TSFloat = { link = "Float" },
            TSFuncBuiltin = { fg = syntax.func, italic = true },
            TSFuncMacro = { link = "Macro" },
            TSFunction = { link = "Function" },
            TSFunctionCall = { fg = syntax.func },
            TSKeyword = { link = "Keyword" },
            TSKeywordFunction = { link = "Keyword" },
            TSKeywordOperator = { fg = syntax.operator },
            TSKeywordReturn = { link = "Keyword" },
            TSLabel = { link = "Label" },
            TSMethod = { fg = syntax.method },
            TSMethodCall = { fg = syntax.method },
            TSNamespace = { fg = syntax.type },
            TSNone = { fg = syntax.variable },
            TSNumber = { link = "Number" },
            TSOperator = { link = "Operator" },
            TSParameter = { fg = syntax.parameter, italic = true },
            TSParameterReference = { link = "TSParameter" },
            TSProperty = { fg = syntax.property },
            TSPunctBracket = { fg = syntax.punctuation },
            TSPunctDelimiter = { fg = syntax.punctuation },
            TSPunctSpecial = { fg = syntax.operator },
            TSRepeat = { link = "Repeat" },
            TSString = { link = "String" },
            TSStringEscape = { fg = syntax.constant },
            TSStringRegex = { fg = syntax.operator },
            TSStringSpecial = { fg = syntax.constant },
            TSSymbol = { fg = syntax.constant },
            TSTag = { fg = syntax.type },
            TSTagAttribute = { fg = syntax.property },
            TSTagDelimiter = { fg = syntax.punctuation },
            TSText = { fg = syntax.variable },
            TSTitle = { fg = syntax.func, bold = true },
            TSType = { link = "Type" },
            TSTypeBuiltin = { fg = syntax.type, italic = true },
            TSTypeDefinition = { link = "Type" },
            TSTypeQualifier = { fg = syntax.keyword },
            TSVariable = { fg = syntax.variable },
            TSVariableBuiltin = { fg = syntax.constant, italic = true },

            ["@attribute"] = { link = "TSAttribute" },
            ["@boolean"] = { link = "TSBoolean" },
            ["@character"] = { link = "TSCharacter" },
            ["@comment"] = { link = "TSComment" },
            ["@constant"] = { link = "TSConstant" },
            ["@constant.builtin"] = { link = "TSConstBuiltin" },
            ["@constant.macro"] = { link = "TSConstMacro" },
            ["@constructor"] = { link = "TSConstructor" },
            ["@function"] = { link = "TSFunction" },
            ["@function.builtin"] = { link = "TSFuncBuiltin" },
            ["@function.call"] = { link = "TSFunctionCall" },
            ["@function.macro"] = { link = "TSFuncMacro" },
            ["@keyword"] = { link = "TSKeyword" },
            ["@keyword.function"] = { link = "TSKeywordFunction" },
            ["@keyword.operator"] = { link = "TSKeywordOperator" },
            ["@keyword.return"] = { link = "TSKeywordReturn" },
            ["@label"] = { link = "TSLabel" },
            ["@method"] = { link = "TSMethod" },
            ["@method.call"] = { link = "TSMethodCall" },
            ["@module"] = { link = "TSNamespace" },
            ["@namespace"] = { link = "TSNamespace" },
            ["@number"] = { link = "TSNumber" },
            ["@operator"] = { link = "TSOperator" },
            ["@parameter"] = { link = "TSParameter" },
            ["@property"] = { link = "TSProperty" },
            ["@punctuation.bracket"] = { link = "TSPunctBracket" },
            ["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
            ["@punctuation.special"] = { link = "TSPunctSpecial" },
            ["@string"] = { link = "TSString" },
            ["@string.escape"] = { link = "TSStringEscape" },
            ["@string.regex"] = { link = "TSStringRegex" },
            ["@string.special"] = { link = "TSStringSpecial" },
            ["@tag"] = { link = "TSTag" },
            ["@tag.attribute"] = { link = "TSTagAttribute" },
            ["@tag.delimiter"] = { link = "TSTagDelimiter" },
            ["@text"] = { link = "TSText" },
            ["@type"] = { link = "TSType" },
            ["@type.builtin"] = { link = "TSTypeBuiltin" },
            ["@type.definition"] = { link = "TSTypeDefinition" },
            ["@type.qualifier"] = { link = "TSTypeQualifier" },
            ["@variable"] = { link = "TSVariable" },
            ["@variable.builtin"] = { link = "TSVariableBuiltin" },
            ["@variable.parameter"] = { link = "TSParameter" },

            ["@lsp.type.class"] = { link = "TSType" },
            ["@lsp.type.decorator"] = { link = "TSFunction" },
            ["@lsp.type.enum"] = { link = "TSType" },
            ["@lsp.type.enumMember"] = { link = "TSProperty" },
            ["@lsp.type.function"] = { link = "TSFunction" },
            ["@lsp.type.interface"] = { link = "TSType" },
            ["@lsp.type.keyword"] = { link = "TSKeyword" },
            ["@lsp.type.macro"] = { link = "TSConstMacro" },
            ["@lsp.type.method"] = { link = "TSMethod" },
            ["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
            ["@lsp.type.namespace"] = { link = "TSNamespace" },
            ["@lsp.type.number"] = { link = "TSNumber" },
            ["@lsp.type.operator"] = { link = "TSOperator" },
            ["@lsp.type.parameter"] = { link = "TSParameter" },
            ["@lsp.type.property"] = { link = "TSProperty" },
            ["@lsp.type.regexp"] = { link = "TSStringRegex" },
            ["@lsp.type.string"] = { link = "TSString" },
            ["@lsp.type.struct"] = { link = "TSType" },
            ["@lsp.type.type"] = { link = "TSType" },
            ["@lsp.type.typeParameter"] = { link = "TSTypeDefinition" },
            ["@lsp.type.variable"] = { link = "TSVariable" },
        },
    })

    vim.cmd("colorscheme rose-pine")
end

M.setup = function()
    rose_wood()
end

return M
