local M = {
    config = function()
        local Color = require("color")

        require("catppuccin").setup({
            flavour = "macchiato",
            -- transparent_background = true,
            color_overrides = {
                macchiato = {
                    rosewater = "#66292F",
                    flamingo = "#8A4B53",
                    red = "#BF472C",
                    maroon = "#ea6962",
                    pink = "#8B3040",
                    mauve = "#C4622D",
                    peach = "#D47D49",
                    yellow = "#F2A766",
                    green = "#F2A766",
                    teal = "#A67458",
                    sky = "#A67458",
                    sapphire = "#A67458",
                    blue = "#D47D49",
                    lavender = "#E0CCAE",
                    text = "#F2DDBC",
                    subtext1 = "#E0CCAE",
                    subtext0 = "#A67458",
                    overlay2 = "#a4896f",
                    overlay1 = "#A4895C",
                    overlay0 = "#6B4035",
                    surface2 = "#3d231a",
                    surface1 = "#291916",
                    surface0 = "#1F1311",
                    base = "#0F0908",
                    mantle = "#121212",
                    crust = "#141617",
                },
            },
            custom_highlights = function(colors)
                return {
                    ["HighlightYank"] = { bg = colors.overlay2 },
                    ["LineNr"] = { fg = colors.overlay0 },
                    ["TabLineFill"] = { bg = Color:from_hex(colors.base):hex() },
                    ["WinBar"] = { bg = "none" }, -- bg = colors.base
                    ["WinSeparator"] = { fg = colors.surface1 },
                    ["StatusLine"] = { bg = "" }, -- Color:from_hex(colors.crust):lighten(4):hex()
                    ["StatusLineNC"] = { bg = "" },
                    ["CommentItalic"] = { fg = colors.overlay1, italic = true },
                    ["CommentBg"] = { bg = colors.base, bold = true, fg = colors.overlay2 },
                    ["StatusLineSeparator"] = { fg = Color:from_hex(colors.base):lighten(8):hex() },
                    ["Folded"] = { link = "TextDimmer" },
                    ["MsgArea"] = { link = "TextDim" },
                    ["ModeMsg"] = { link = "TextDim" },
                    ["CodeLensSeparator"] = { fg = colors.surface0 },
                    ["CodeLensContentIcon"] = { fg = colors.green, bg = colors.surface0 },
                    ["CodeLensContent"] = { fg = colors.overlay0, bg = colors.surface0, italic = true },
                    ["StatusLineGreenTextNoBg"] = { link = "DiagnosticInfoTextNoBg" },
                    ["StatusLineGreenTextWithBg"] = { link = "DiagnosticInfoTextWithBg" },
                    ["StatusLineYellowTextNoBg"] = { link = "DiagnosticWarnTextNoBg" },
                    ["StatusLineYellowTextWithBg"] = { link = "DiagnosticWarnTextWithBg" },
                    ["StatusLineRedTextNoBg"] = { link = "DiagnosticErrorTextNoBg" },
                    ["StatusLineRedTextWithBg"] = { link = "DiagnosticErrorTextWithBg" },
                    ["DiagnosticInfoTextNoBg"] = { fg = "#354137" },
                    ["DiagnosticInfoTextWithBg"] = { fg = "#89B483", bg = "#354137", italic = true },
                    ["DiagnosticErrorTextNoBg"] = { fg = "#4A3030" },
                    ["DiagnosticErrorTextWithBg"] = { fg = "#EA6963", bg = "#4A3030", italic = true },
                    ["DiagnosticWarnTextNoBg"] = { fg = "#463D2E" },
                    ["DiagnosticWarnTextWithBg"] = { fg = "#D8A658", bg = "#463D2E", italic = true },
                    ["DiagnosticHintTextNoBg"] = { fg = "#354137" },
                    ["DiagnosticHintTextWithBg"] = { fg = "#89B483", bg = "#354137", italic = true },

                    ["OutlineGuides"] = { link = "TextDimmer" },
                    ["OutlineFoldMarker"] = { link = "TextDimmer" },

                    -- Multi-dot diagnostic highlights (for displaying multiple diagnostic types on same line)
                    -- Error background combinations
                    ["DiagnosticErrorDotOnErrorBg"] = { fg = "#EA6963", bg = "#4A3030", italic = true },
                    ["DiagnosticWarnDotOnErrorBg"] = { fg = "#D8A658", bg = "#4A3030", italic = true },
                    ["DiagnosticInfoDotOnErrorBg"] = { fg = "#89B483", bg = "#4A3030", italic = true },
                    ["DiagnosticHintDotOnErrorBg"] = { fg = "#89B483", bg = "#4A3030", italic = true },

                    -- Warn background combinations
                    ["DiagnosticErrorDotOnWarnBg"] = { fg = "#EA6963", bg = "#463D2E", italic = true },
                    ["DiagnosticWarnDotOnWarnBg"] = { fg = "#D8A658", bg = "#463D2E", italic = true },
                    ["DiagnosticInfoDotOnWarnBg"] = { fg = "#89B483", bg = "#463D2E", italic = true },
                    ["DiagnosticHintDotOnWarnBg"] = { fg = "#89B483", bg = "#463D2E", italic = true },

                    -- Info background combinations
                    ["DiagnosticErrorDotOnInfoBg"] = { fg = "#EA6963", bg = "#354137", italic = true },
                    ["DiagnosticWarnDotOnInfoBg"] = { fg = "#D8A658", bg = "#354137", italic = true },
                    ["DiagnosticInfoDotOnInfoBg"] = { fg = "#89B483", bg = "#354137", italic = true },
                    ["DiagnosticHintDotOnInfoBg"] = { fg = "#89B483", bg = "#354137", italic = true },

                    -- Hint background combinations (same as Info since they share colors)
                    ["DiagnosticErrorDotOnHintBg"] = { fg = "#EA6963", bg = "#354137", italic = true },
                    ["DiagnosticWarnDotOnHintBg"] = { fg = "#D8A658", bg = "#354137", italic = true },
                    ["DiagnosticInfoDotOnHintBg"] = { fg = "#89B483", bg = "#354137", italic = true },
                    ["DiagnosticHintDotOnHintBg"] = { fg = "#89B483", bg = "#354137", italic = true },

                    ["StatusLineSeparatorContent"] = {
                        fg = colors.subtext1,
                        bg = Color:from_hex(colors.base):lighten(8):hex(),
                    },
                    ["StatuslineSeparatorLsp"] = {
                        fg = "#928375",
                        bg = Color:from_hex(colors.base):lighten(8):hex(),
                    },
                    ["NormalMode"] = { fg = "#F2A766" },
                    ["ReplaceMode"] = { fg = "#ea6963" },
                    ["CommandMode"] = { fg = "#e78a4f" },
                    ["PendingMode"] = { fg = "#D8A658" },
                    ["InsertMode"] = { fg = "#a9b666" },
                    ["VisualMode"] = { fg = "#D3869C" },
                    ["MiniFilesTitleFocused"] = { link = "FloatTitle" },
                    ["MiniIndentscopeSymbol"] = { link = "TextDimmest" },
                    ["Text"] = { fg = colors.text },
                    ["TextDim"] = { fg = "#928375" },
                    ["TextDimmer"] = { fg = Color:from_hex("#928375"):darken(22):hex() },
                    ["TextDimmest"] = { fg = Color:from_hex("#928375"):darken(33):hex() },
                    CmpItemMenu = { fg = colors.surface2 },
                    CursorLineNr = { fg = colors.text },
                    NormalFloat = { bg = colors.mantle }, -- bg = Color:from_hex(colors.crust):lighten(3):hex()
                    FloatBorder = { bg = colors.mantle, fg = colors.surface0 }, -- bg = Color:from_hex(colors.crust):lighten(3):hex(),
                    FloatTitle = {
                        bg = Color:from_hex(colors.crust):lighten(3):hex(),
                        fg = colors.green,
                        style = { "bold" },
                    },
                    BlinkCmpMenuBorder = { fg = colors.surface0 },
                    CursorLine = { bg = "#303030" },
                    Visual = { bg = "#303030" },
                    BlinkCmpMenuSelection = { bg = "#303030" },
                    Pmenu = { bg = colors.mantle, fg = "" },
                    PmenuSel = { bg = colors.surface0, fg = colors.green },
                    GitSignsChange = { fg = colors.peach },
                    -- LineNr = { fg = colors.overlay0 },
                    LspInfoBorder = { link = "FloatBorder" },
                    NeoTreeDirectoryIcon = { fg = colors.subtext1 },
                    NeoTreeDirectoryName = { fg = colors.subtext1 },
                    NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
                    NeoTreeGitConflict = { fg = colors.red },
                    NeoTreeGitDeleted = { fg = colors.red },
                    NeoTreeGitIgnored = { fg = colors.overlay0 },
                    NeoTreeGitModified = { fg = colors.peach },
                    NeoTreeGitStaged = { fg = colors.green },
                    NeoTreeGitUnstaged = { fg = colors.red },
                    NeoTreeGitUntracked = { fg = colors.green },
                    NeoTreeIndent = { fg = colors.surface1 },
                    NeoTreeNormal = { bg = colors.mantle },
                    NeoTreeNormalNC = { bg = colors.mantle },
                    NeoTreeRootName = { fg = colors.subtext1, style = { "bold" } },
                    NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
                    NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
                    NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
                    NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
                    NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
                    TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
                    TelescopePreviewNormal = { bg = colors.crust },
                    TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
                    TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
                    TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
                    TelescopePromptNormal = { bg = colors.surface0 },
                    TelescopePromptPrefix = { bg = colors.surface0 },
                    TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
                    TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
                    TelescopeResultsNormal = { bg = colors.mantle },
                    TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
                    TelescopeSelection = { bg = colors.surface0 },
                    VertSplit = { bg = colors.base, fg = colors.surface0 },
                    WhichKeyFloat = { bg = colors.mantle },
                    YankHighlight = { bg = colors.surface2 },
                    FidgetTask = { fg = colors.subtext2 },
                    FidgetTitle = { fg = colors.peach },

                    IblIndent = { fg = colors.surface0 },
                    IblScope = { fg = colors.overlay0 },

                    Boolean = { fg = colors.mauve },
                    Number = { fg = colors.mauve },
                    Float = { fg = colors.mauve },

                    PreProc = { fg = colors.mauve },
                    PreCondit = { fg = colors.mauve },
                    Include = { fg = colors.mauve },
                    Define = { fg = colors.mauve },
                    Conditional = { fg = colors.red },
                    Repeat = { fg = colors.red },
                    Keyword = { fg = colors.red, italic = true },
                    Typedef = { fg = colors.red },
                    Exception = { fg = colors.red },
                    Statement = { fg = colors.red },

                    Error = { fg = colors.red },
                    StorageClass = { fg = colors.peach },
                    Tag = { fg = colors.peach },
                    Label = { fg = colors.peach },
                    Structure = { fg = colors.peach },
                    Operator = { fg = colors.peach },
                    Title = { fg = colors.peach },
                    Special = { fg = colors.yellow },
                    SpecialChar = { fg = colors.yellow },
                    Type = { fg = colors.yellow },
                    Function = { fg = colors.green },
                    Delimiter = { fg = colors.subtext2 },
                    Ignore = { fg = colors.subtext2 },
                    Macro = { fg = colors.teal },

                    TSAnnotation = { fg = colors.mauve },
                    TSAttribute = { fg = colors.mauve },
                    TSBoolean = { fg = colors.mauve },
                    TSCharacter = { fg = colors.teal },
                    TSCharacterSpecial = { link = "SpecialChar" },
                    TSComment = { link = "Comment" },
                    TSConditional = { fg = colors.red },
                    TSConstBuiltin = { fg = colors.mauve },
                    TSConstMacro = { fg = colors.mauve },
                    TSConstant = { fg = colors.text },
                    TSConstructor = { fg = colors.green },
                    TSDebug = { link = "Debug" },
                    TSDefine = { link = "Define" },
                    TSEnvironment = { link = "Macro" },
                    TSEnvironmentName = { link = "Type" },
                    TSError = { link = "Error" },
                    TSException = { fg = colors.red },
                    TSField = { fg = colors.blue },
                    TSFloat = { fg = colors.mauve },
                    TSFuncBuiltin = { fg = colors.green },
                    TSFuncMacro = { fg = colors.green },
                    TSFunction = { fg = colors.green },
                    TSFunctionCall = { fg = colors.green },
                    TSInclude = { fg = colors.red },
                    TSKeyword = { fg = colors.red, italic = true },
                    TSKeywordFunction = { fg = colors.red, italic = true },
                    TSKeywordOperator = { fg = colors.peach },
                    TSKeywordReturn = { fg = colors.red },
                    TSLabel = { fg = colors.peach },
                    TSLiteral = { link = "String" },
                    TSMath = { fg = colors.blue },
                    TSMethod = { fg = colors.green },
                    TSMethodCall = { fg = colors.green },
                    TSNamespace = { fg = colors.yellow },
                    TSNone = { fg = colors.text },
                    TSNumber = { fg = colors.mauve },
                    TSOperator = { fg = colors.peach },
                    TSParameter = { fg = colors.text },
                    TSParameterReference = { fg = colors.text },
                    TSPreProc = { link = "PreProc" },
                    TSProperty = { fg = colors.blue },
                    TSPunctBracket = { fg = colors.text },
                    TSPunctDelimiter = { link = "Delimiter" },
                    TSPunctSpecial = { fg = colors.blue },
                    TSRepeat = { fg = colors.red },
                    TSStorageClass = { fg = colors.peach },
                    TSStorageClassLifetime = { fg = colors.peach },
                    TSStrike = { fg = colors.subtext2 },
                    TSString = { fg = colors.teal },
                    TSStringEscape = { fg = colors.green },
                    TSStringRegex = { fg = colors.green },
                    TSStringSpecial = { link = "SpecialChar" },
                    TSSymbol = { fg = colors.text },
                    TSTag = { fg = colors.peach },
                    TSTagAttribute = { fg = colors.green },
                    TSTagDelimiter = { fg = colors.green },
                    TSText = { fg = colors.green },
                    TSTextReference = { link = "Constant" },
                    TSTitle = { link = "Title" },
                    TSTodo = { link = "Todo" },
                    TSType = { fg = colors.yellow },
                    TSTypeBuiltin = { fg = colors.yellow },
                    TSTypeDefinition = { fg = colors.yellow },
                    TSTypeQualifier = { fg = colors.peach },
                    TSURI = { fg = colors.blue },
                    TSVariable = { fg = colors.text },
                    TSVariableBuiltin = { fg = colors.mauve },

                    ["@annotation"] = { link = "TSAnnotation" },
                    ["@attribute"] = { link = "TSAttribute" },
                    ["@boolean"] = { link = "TSBoolean" },
                    ["@character"] = { link = "TSCharacter" },
                    ["@character.special"] = { link = "TSCharacterSpecial" },
                    ["@comment"] = { link = "TSComment" },
                    ["@conceal"] = { link = "Grey" },
                    ["@conditional"] = { link = "TSConditional" },
                    ["@constant"] = { link = "TSConstant" },
                    ["@constant.builtin"] = { link = "TSConstBuiltin" },
                    ["@constant.macro"] = { link = "TSConstMacro" },
                    ["@constructor"] = { link = "TSConstructor" },
                    ["@debug"] = { link = "TSDebug" },
                    ["@define"] = { link = "TSDefine" },
                    ["@error"] = { link = "TSError" },
                    ["@exception"] = { link = "TSException" },
                    ["@field"] = { link = "TSField" },
                    ["@float"] = { link = "TSFloat" },
                    ["@function"] = { link = "TSFunction" },
                    ["@function.builtin"] = { link = "TSFuncBuiltin" },
                    ["@function.call"] = { link = "TSFunctionCall" },
                    ["@function.macro"] = { link = "TSFuncMacro" },
                    ["@include"] = { link = "TSInclude" },
                    ["@keyword"] = { link = "TSKeyword" },
                    ["@keyword.function"] = { link = "TSKeywordFunction" },
                    ["@keyword.operator"] = { link = "TSKeywordOperator" },
                    ["@keyword.return"] = { link = "TSKeywordReturn" },
                    ["@label"] = { link = "TSLabel" },
                    ["@math"] = { link = "TSMath" },
                    ["@method"] = { link = "TSMethod" },
                    ["@method.call"] = { link = "TSMethodCall" },
                    ["@namespace"] = { link = "TSNamespace" },
                    ["@none"] = { link = "TSNone" },
                    ["@number"] = { link = "TSNumber" },
                    ["@operator"] = { link = "TSOperator" },
                    ["@parameter"] = { link = "TSParameter" },
                    ["@parameter.reference"] = { link = "TSParameterReference" },
                    ["@preproc"] = { link = "TSPreProc" },
                    ["@property"] = { link = "TSProperty" },
                    ["@punctuation.bracket"] = { link = "TSPunctBracket" },
                    ["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
                    ["@punctuation.special"] = { link = "TSPunctSpecial" },
                    ["@repeat"] = { link = "TSRepeat" },
                    ["@storageclass"] = { link = "TSStorageClass" },
                    ["@storageclass.lifetime"] = { link = "TSStorageClassLifetime" },
                    ["@strike"] = { link = "TSStrike" },
                    ["@string"] = { link = "TSString" },
                    ["@string.escape"] = { link = "TSStringEscape" },
                    ["@string.regex"] = { link = "TSStringRegex" },
                    ["@string.special"] = { link = "TSStringSpecial" },
                    ["@symbol"] = { link = "TSSymbol" },
                    ["@tag"] = { link = "TSTag" },
                    ["@tag.attribute"] = { link = "TSTagAttribute" },
                    ["@tag.delimiter"] = { link = "TSTagDelimiter" },
                    ["@text"] = { link = "TSText" },
                    ["@text.danger"] = { link = "TSDanger" },
                    ["@text.diff.add"] = { link = "diffAdded" },
                    ["@text.diff.delete"] = { link = "diffRemoved" },
                    ["@text.emphasis"] = { link = "TSEmphasis" },
                    ["@text.environment"] = { link = "TSEnvironment" },
                    ["@text.environment.name"] = { link = "TSEnvironmentName" },
                    ["@text.literal"] = { link = "TSLiteral" },
                    ["@text.math"] = { link = "TSMath" },
                    ["@text.note"] = { link = "TSNote" },
                    ["@text.reference"] = { link = "TSTextReference" },
                    ["@text.strike"] = { link = "TSStrike" },
                    ["@text.strong"] = { link = "TSStrong" },
                    ["@text.title"] = { link = "TSTitle" },
                    ["@text.todo"] = { link = "TSTodo" },
                    ["@text.todo.checked"] = { link = "Green" },
                    ["@text.todo.unchecked"] = { link = "Ignore" },
                    ["@text.underline"] = { link = "TSUnderline" },
                    ["@text.uri"] = { link = "TSURI" },
                    ["@text.warning"] = { link = "TSWarning" },
                    ["@todo"] = { link = "TSTodo" },
                    ["@type"] = { link = "TSType" },
                    ["@type.builtin"] = { link = "TSTypeBuiltin" },
                    ["@type.definition"] = { link = "TSTypeDefinition" },
                    ["@type.qualifier"] = { link = "TSTypeQualifier" },
                    ["@uri"] = { link = "TSURI" },
                    ["@variable"] = { link = "TSVariable" },
                    ["@variable.builtin"] = { link = "TSVariableBuiltin" },

                    ["@lsp.type.class"] = { link = "TSType" },
                    ["@lsp.type.comment"] = { link = "TSComment" },
                    ["@lsp.type.decorator"] = { link = "TSFunction" },
                    ["@lsp.type.enum"] = { link = "TSType" },
                    ["@lsp.type.enumMember"] = { link = "TSProperty" },
                    ["@lsp.type.events"] = { link = "TSLabel" },
                    ["@lsp.type.function"] = { link = "TSFunction" },
                    ["@lsp.type.interface"] = { link = "TSType" },
                    ["@lsp.type.keyword"] = { link = "TSKeyword" },
                    ["@lsp.type.macro"] = { link = "TSConstMacro" },
                    ["@lsp.type.method"] = { link = "TSMethod" },
                    ["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
                    ["@lsp.type.namespace"] = { link = "TSNamespace" },
                    ["@lsp.type.number"] = { link = "TSNumber" },
                    ["@lsp.type.operator"] = { link = "TSOperator" },
                    ["@lsp.type.parameter"] = { link = "TSParameter" },
                    ["@lsp.type.property"] = { link = "TSProperty" },
                    ["@lsp.type.regexp"] = { link = "TSStringRegex" },
                    ["@lsp.type.string"] = { link = "TSString" },
                    ["@lsp.type.struct"] = { link = "TSType" },
                    ["@lsp.type.type"] = { link = "TSType" },
                    ["@lsp.type.typeParameter"] = { link = "TSTypeDefinition" },
                    ["@lsp.type.variable"] = { link = "TSVariable" },
                }
            end,
        })

        vim.cmd.colorscheme("catppuccin")
    end,
}

return M
